import { createId, nowIso } from "./ids";
import type { ChatMessage, ConceptSuggestion, KnowledgeNode, MindSteedState } from "./types";

export function createInitialState(): MindSteedState {
  const now = nowIso();
  const rootId = createId("node");
  const childA = createId("node");
  const childB = createId("node");
  const messageId = createId("msg");

  const nodes: KnowledgeNode[] = [
    {
      id: rootId,
      parentId: null,
      rootId,
      title: "意马学习法",
      summary: "把一个主题拆成可对话、可延展、可同步到 Obsidian 的知识树。",
      sourceText: "如何把 AI 对话沉淀成长期可复用的知识网络？",
      sourceMessageId: null,
      creationMethod: "root",
      nodeType: "root",
      childOrder: 0,
      pendingAutoPrompt: false,
      titleAutoGenerated: false,
      titleManuallyEdited: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: childA,
      parentId: rootId,
      rootId,
      title: "节点式对话",
      summary: "每个节点承载一个聚焦问题，回答后继续生成可展开的学习分支。",
      sourceText: "从根主题拆出的第一个核心能力。",
      sourceMessageId: null,
      creationMethod: "suggestion",
      nodeType: "concept",
      childOrder: 0,
      pendingAutoPrompt: false,
      titleAutoGenerated: false,
      titleManuallyEdited: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: childB,
      parentId: rootId,
      rootId,
      title: "Obsidian 同步",
      summary: "将知识树写入 Markdown，并保留用户手写笔记区。",
      sourceText: "从根主题拆出的第二个核心能力。",
      sourceMessageId: null,
      creationMethod: "suggestion",
      nodeType: "concept",
      childOrder: 1,
      pendingAutoPrompt: false,
      titleAutoGenerated: false,
      titleManuallyEdited: false,
      createdAt: now,
      updatedAt: now,
    },
  ];

  const messages: ChatMessage[] = [
    {
      id: messageId,
      nodeId: rootId,
      role: "assistant",
      content:
        "欢迎使用 OpenMindSteed。这个原型已经可以创建知识树、展开分支、模拟 AI 回答，并生成 Obsidian Markdown 同步包。",
      status: "complete",
      createdAt: now,
    },
  ];

  const suggestions: ConceptSuggestion[] = [
    {
      id: createId("sug"),
      nodeId: rootId,
      label: "学习路径设计",
      reason: "先明确一个主题如何被拆成可执行的学习步骤。",
      priority: 1,
      difficulty: "beginner",
      relation: "child",
      status: "suggested",
      createdAt: now,
    },
    {
      id: createId("sug"),
      nodeId: rootId,
      label: "知识回流",
      reason: "理解 Obsidian 如何承接 AI 生成内容和个人笔记。",
      priority: 2,
      difficulty: "intermediate",
      relation: "child",
      status: "suggested",
      createdAt: now,
    },
  ];

  return {
    nodes,
    messages,
    suggestions,
    codexThreads: [],
    selectedNodeId: rootId,
    streamingNodeIds: [],
    settings: {
      provider: {
        provider: "mock",
        providerPreset: "custom",
        endpoint: "https://api.openai.com/v1",
        apiKey: "",
        model: "gpt-5.4-mini",
        codexBin: "",
        webSearch: false,
        generateImage: false,
      },
      obsidian: {
        vaultPath: "",
        autoSync: false,
        lastSyncAt: null,
        lastSyncStatus: null,
      },
      theme: "dark",
    },
  };
}
