export type NodeId = string;
export type MessageId = string;
export type SuggestionId = string;

export type ChatIntent = "root_start" | "branch_start" | "follow_up" | "follow_up_as_branch";

export type NodeCreationMethod =
  | "root"
  | "manual"
  | "suggestion"
  | "selection"
  | "follow_up_branch";

export interface KnowledgeNode {
  id: NodeId;
  parentId: NodeId | null;
  rootId: NodeId;
  title: string;
  summary: string;
  sourceText: string | null;
  sourceMessageId: MessageId | null;
  creationMethod: NodeCreationMethod;
  nodeType: "root" | "concept";
  childOrder: number;
  pendingAutoPrompt: boolean;
  titleAutoGenerated: boolean;
  titleManuallyEdited: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface ChatMessage {
  id: MessageId;
  nodeId: NodeId;
  role: "user" | "assistant" | "system";
  content: string;
  status: "streaming" | "complete" | "error";
  createdAt: string;
}

export interface ConceptSuggestion {
  id: SuggestionId;
  nodeId: NodeId;
  label: string;
  reason: string;
  priority: number;
  difficulty: "beginner" | "intermediate" | "advanced";
  relation: string;
  status: "suggested" | "expanded" | "dismissed";
  createdAt: string;
}

export interface NodeContext {
  id: string;
  title: string;
  summary: string;
}

export interface RecentMessageContext {
  role: string;
  content: string;
}

export interface ImageGenerationOptions {
  size?: string;
  quality?: string;
  format?: string;
}

export interface ChatToolRequest {
  webSearch: boolean;
  generateImage: boolean;
  imageGeneration?: ImageGenerationOptions;
}

export interface ChatImageInput {
  mimeType: string;
  dataBase64: string;
  filename?: string;
}

export interface ChatStreamRequest {
  node: NodeContext;
  parent?: NodeContext;
  root?: NodeContext;
  recentMessages: RecentMessageContext[];
  userMessage: string;
  intent: ChatIntent;
  sourceText?: string;
  locale: string;
  tools?: ChatToolRequest;
  imageInputs: ChatImageInput[];
  codexThreadId?: string;
}

export interface APISuggestion {
  label: string;
  reason: string;
  priority: number;
  difficulty: "beginner" | "intermediate" | "advanced";
  relation: string;
}

export interface GeneratedImage {
  id: string;
  url: string;
  mimeType: string;
  sourceUrl?: string;
  localPath?: string;
  byteLength?: number;
  storedAt?: string;
  prompt?: string;
  size?: string;
  quality?: string;
}

export type ProviderKind = "mock" | "byok" | "codex-local";

export type ProviderPresetId =
  | "custom"
  | "deepseek"
  | "qwen-global"
  | "qwen-china"
  | "zhipu"
  | "kimi"
  | "doubao";

export interface ProviderSettings {
  provider: ProviderKind;
  providerPreset: ProviderPresetId;
  endpoint: string;
  apiKey: string;
  model: string;
  codexBin: string;
  webSearch: boolean;
  generateImage: boolean;
}

export interface ObsidianSettings {
  vaultPath: string;
  autoSync: boolean;
  lastSyncAt: string | null;
  lastSyncStatus: string | null;
}

export interface AppSettings {
  provider: ProviderSettings;
  obsidian: ObsidianSettings;
  theme: "dark" | "light";
}

export interface CodexThreadMapping {
  nodeId: NodeId;
  threadId: string;
  createdAt: string;
  lastUsedAt: string;
}

export interface MindSteedState {
  nodes: KnowledgeNode[];
  messages: ChatMessage[];
  suggestions: ConceptSuggestion[];
  codexThreads: CodexThreadMapping[];
  selectedNodeId: NodeId | null;
  streamingNodeIds: string[];
  settings: AppSettings;
}
