import { describe, expect, it } from "vitest";
import { createInitialState } from "../../domain/sampleData";
import {
  buildObsidianPackage,
  managedEnd,
  managedStart,
  mergeManagedDocument,
  safeFileComponent,
} from "./export";

describe("Obsidian export", () => {
  it("builds a vault index, tree index, and node notes", () => {
    const state = createInitialState();
    const pkg = buildObsidianPackage(state, new Date("2026-06-23T17:00:00.000Z"));

    expect(pkg.treeCount).toBe(1);
    expect(pkg.nodeCount).toBe(3);
    expect(pkg.scope).toEqual({ kind: "vault", rootId: null });
    expect(pkg.files.some((file) => file.relativePath === "Index.md")).toBe(true);
    expect(pkg.files.filter((file) => file.kind === "node")).toHaveLength(3);
    expect(pkg.assets).toEqual([]);
    expect(pkg.files.every((file) => file.contents.includes(managedStart))).toBe(true);
  });

  it("uses safe relative paths for the backend sync payload", () => {
    const state = createInitialState();
    const pkg = buildObsidianPackage(state, new Date("2026-06-23T17:00:00.000Z"));

    for (const file of pkg.files) {
      expect(file.relativePath.startsWith("/")).toBe(false);
      expect(file.relativePath.includes("..")).toBe(false);
      expect(file.relativePath.endsWith(".md")).toBe(true);
      expect(file.sourceId).not.toBe("");
      expect(["vaultIndex", "treeIndex", "node"]).toContain(file.kind);
    }
    for (const asset of pkg.assets) {
      expect(asset.relativePath.startsWith("/")).toBe(false);
      expect(asset.relativePath.includes("..")).toBe(false);
      expect(asset.relativePath.includes("/Assets/")).toBe(true);
      expect(asset.sourcePath).not.toBe("");
      expect(asset.kind).toBe("generatedImage");
    }
  });

  it("can build a package for only one selected tree", () => {
    const state = createInitialState();
    const now = "2026-06-23T17:00:00.000Z";
    state.nodes.push(
      {
        id: "node-second-root",
        parentId: null,
        rootId: "node-second-root",
        title: "Second Tree",
        summary: "",
        sourceText: null,
        sourceMessageId: null,
        creationMethod: "root",
        nodeType: "root",
        childOrder: 1,
        pendingAutoPrompt: false,
        titleAutoGenerated: false,
        titleManuallyEdited: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "node-second-child",
        parentId: "node-second-root",
        rootId: "node-second-root",
        title: "Second Child",
        summary: "",
        sourceText: null,
        sourceMessageId: null,
        creationMethod: "manual",
        nodeType: "concept",
        childOrder: 0,
        pendingAutoPrompt: false,
        titleAutoGenerated: false,
        titleManuallyEdited: false,
        createdAt: now,
        updatedAt: now,
      },
    );

    const pkg = buildObsidianPackage(state, new Date(now), {
      rootId: "node-second-root",
    });

    expect(pkg.treeCount).toBe(1);
    expect(pkg.nodeCount).toBe(2);
    expect(pkg.scope).toEqual({ kind: "tree", rootId: "node-second-root" });
    expect(pkg.files.some((file) => file.relativePath === "Index.md")).toBe(false);
    expect(pkg.files.every((file) => file.relativePath.includes("Second Tree"))).toBe(true);
    expect(pkg.files.every((file) => file.rootId === "node-second-root")).toBe(true);
    expect(pkg.files.some((file) => file.sourceId === "node-second-child")).toBe(true);
  });

  it("escapes WikiLink aliases and generated filenames for Obsidian", () => {
    const state = createInitialState();
    state.nodes[0] = {
      ...state.nodes[0],
      title: "Root | [bad]\nName",
    };
    state.nodes[1] = {
      ...state.nodes[1],
      title: "Child [[alias]] | pipe",
    };
    state.nodes[2] = {
      ...state.nodes[2],
      title: 'Leaf #tag / path "x"',
    };

    const pkg = buildObsidianPackage(state, new Date("2026-06-23T17:00:00.000Z"));
    const wikiLinks = pkg.files.flatMap(
      (file) => file.contents.match(/\[\[[^\]\n\r]+\]\]/gu) ?? [],
    );

    expect(wikiLinks.length).toBeGreaterThan(0);
    for (const file of pkg.files) {
      expect(file.relativePath).not.toMatch(/[|#[\]\n\r]/u);
      expect(file.relativePath).not.toContain("..");
    }
    for (const link of wikiLinks) {
      const body = link.slice(2, -2);
      const parts = body.split("|");
      expect(parts).toHaveLength(parts.length === 1 ? 1 : 2);
      expect(parts[0]).not.toMatch(/[|[\]\n\r]/u);
      if (parts[1]) {
        expect(parts[1]).not.toMatch(/[|[\]\n\r]/u);
      }
    }
  });

  it("preserves user notes when replacing a managed block", () => {
    const existing = `${managedStart}\nold generated\n${managedEnd}\n\n## My Notes\n\nkeep this`;
    const merged = mergeManagedDocument("new generated", existing);

    expect(merged).toContain("new generated");
    expect(merged).not.toContain("old generated");
    expect(merged).toContain("keep this");
  });

  it("wraps unmanaged existing content under My Notes", () => {
    const merged = mergeManagedDocument("generated", "personal note");

    expect(merged).toContain("generated");
    expect(merged).toContain("## My Notes");
    expect(merged).toContain("personal note");
  });

  it("renders generated image messages as Markdown image embeds", () => {
    const state = createInitialState();
    const nodeId = state.selectedNodeId!;
    state.messages.push({
      id: "msg-image",
      nodeId,
      role: "assistant",
      status: "complete",
      createdAt: "2026-06-23T18:00:00.000Z",
      content: `__mindsteed_generated_image__:${JSON.stringify({
        id: "img-a",
        url: "asset://localhost/generated-image",
        mimeType: "image/png",
        sourceUrl: "https://provider.example.com/image.png",
        localPath: "/Users/me/Library/Application Support/OpenMindSteed/generated-images/img-a.png",
        prompt: "diagram",
      })}`,
    });

    const pkg = buildObsidianPackage(state, new Date("2026-06-23T18:00:00.000Z"));
    const nodeNote = pkg.files.find((file) => file.kind === "node" && file.sourceId === nodeId);

    expect(pkg.assets).toHaveLength(1);
    expect(pkg.assets[0]).toMatchObject({
      kind: "generatedImage",
      sourceId: "img-a",
      sourcePath: "/Users/me/Library/Application Support/OpenMindSteed/generated-images/img-a.png",
      mimeType: "image/png",
    });
    expect(pkg.assets[0].relativePath).toContain("/Assets/");
    expect(nodeNote?.contents).toContain("![diagram](<../Assets/");
    expect(nodeNote?.contents).toContain("Source URL: https://provider.example.com/image.png");
    expect(nodeNote?.contents).not.toContain("__mindsteed_generated_image__:");
  });

  it("sanitizes filenames for Obsidian", () => {
    expect(safeFileComponent(' bad/name:with*chars? "x" ')).toBe("bad-name-with-chars-x");
  });
});
