import {
  createContext,
  type Dispatch,
  type ReactNode,
  useContext,
  useEffect,
  useMemo,
  useReducer,
  useRef,
} from "react";
import { createId, nowIso } from "../domain/ids";
import { createInitialState } from "../domain/sampleData";
import { childrenOf, descendantsOf, rootNodes } from "../domain/selectors";
import type {
  APISuggestion,
  AppSettings,
  ChatMessage,
  ConceptSuggestion,
  KnowledgeNode,
  MindSteedState,
  NodeCreationMethod,
  NodeId,
} from "../domain/types";
import { loadPersistedState, loadStateFromBrowser, savePersistedState } from "./persistence";

type Action =
  | { type: "hydrate"; state: MindSteedState }
  | { type: "select-node"; nodeId: NodeId }
  | { type: "create-root"; seedText: string }
  | {
      type: "create-child";
      parentId: NodeId;
      title: string;
      method: NodeCreationMethod;
      sourceText?: string | null;
      sourceMessageId?: string | null;
    }
  | { type: "rename-node"; nodeId: NodeId; title: string }
  | { type: "delete-node"; nodeId: NodeId; cascade: boolean }
  | { type: "add-message"; message: ChatMessage }
  | { type: "update-message"; messageId: string; patch: Partial<ChatMessage> }
  | { type: "set-streaming"; nodeId: NodeId; streaming: boolean }
  | { type: "update-node"; nodeId: NodeId; patch: Partial<KnowledgeNode> }
  | { type: "replace-suggestions"; nodeId: NodeId; suggestions: APISuggestion[] }
  | { type: "mark-suggestion-expanded"; suggestionId: string }
  | { type: "set-codex-thread"; nodeId: NodeId; threadId: string }
  | { type: "update-settings"; patch: Partial<AppSettings> }
  | { type: "record-sync-status"; status: string }
  | { type: "reset-demo" };

interface MindSteedContextValue {
  state: MindSteedState;
  dispatch: Dispatch<Action>;
  actions: {
    createRoot(seedText: string): void;
    createChild(
      parentId: NodeId,
      title: string,
      method: NodeCreationMethod,
      sourceText?: string | null,
      sourceMessageId?: string | null,
    ): void;
    renameNode(nodeId: NodeId, title: string): void;
    deleteNode(nodeId: NodeId, cascade: boolean): void;
  };
}

const MindSteedContext = createContext<MindSteedContextValue | null>(null);

function reducer(state: MindSteedState, action: Action): MindSteedState {
  switch (action.type) {
    case "hydrate":
      return action.state;

    case "select-node":
      return { ...state, selectedNodeId: action.nodeId };

    case "create-root": {
      const now = nowIso();
      const trimmed = action.seedText.trim();
      const title = trimmed.length > 0 ? trimmed.slice(0, 32) : "新的学习主题";
      const id = createId("node");
      const node: KnowledgeNode = {
        id,
        parentId: null,
        rootId: id,
        title,
        summary: "",
        sourceText: trimmed || null,
        sourceMessageId: null,
        creationMethod: "root",
        nodeType: "root",
        childOrder: rootNodes(state.nodes).length,
        pendingAutoPrompt: trimmed.length > 0,
        titleAutoGenerated: false,
        titleManuallyEdited: false,
        createdAt: now,
        updatedAt: now,
      };
      return {
        ...state,
        nodes: [node, ...state.nodes],
        selectedNodeId: id,
      };
    }

    case "create-child": {
      const parent = state.nodes.find((node) => node.id === action.parentId);
      if (!parent) return state;
      const now = nowIso();
      const childCount = childrenOf(state.nodes, parent.id).length;
      const id = createId("node");
      const child: KnowledgeNode = {
        id,
        parentId: parent.id,
        rootId: parent.rootId,
        title: action.title.trim().slice(0, 48) || "新分支",
        summary: "",
        sourceText: action.sourceText ?? null,
        sourceMessageId: action.sourceMessageId ?? null,
        creationMethod: action.method,
        nodeType: "concept",
        childOrder: childCount,
        pendingAutoPrompt: true,
        titleAutoGenerated: false,
        titleManuallyEdited: false,
        createdAt: now,
        updatedAt: now,
      };
      return {
        ...state,
        nodes: state.nodes
          .map((node) => (node.id === parent.id ? { ...node, updatedAt: now } : node))
          .concat(child),
        selectedNodeId: child.id,
      };
    }

    case "rename-node": {
      const title = action.title.trim().slice(0, 48);
      if (!title) return state;
      const now = nowIso();
      return {
        ...state,
        nodes: state.nodes.map((node) =>
          node.id === action.nodeId
            ? {
                ...node,
                title,
                titleManuallyEdited: true,
                updatedAt: now,
              }
            : node,
        ),
      };
    }

    case "delete-node": {
      const target = state.nodes.find((node) => node.id === action.nodeId);
      if (!target) return state;
      const directChildren = childrenOf(state.nodes, target.id);
      const affected = action.cascade
        ? new Set([target.id, ...descendantsOf(state.nodes, target.id).map((node) => node.id)])
        : new Set([target.id]);

      let nodes = state.nodes.filter((node) => !affected.has(node.id));
      if (!action.cascade) {
        nodes = nodes.map((node) =>
          node.parentId === target.id
            ? {
                ...node,
                parentId: target.parentId,
                rootId: target.parentId ? target.rootId : node.id,
                nodeType: target.parentId ? "concept" : "root",
                updatedAt: nowIso(),
              }
            : node,
        );
      }

      const replacement =
        target.parentId && !affected.has(target.parentId)
          ? target.parentId
          : (directChildren.find((child) => !affected.has(child.id))?.id ??
            rootNodes(nodes)[0]?.id ??
            null);

      return {
        ...state,
        nodes,
        messages: state.messages.filter((message) => !affected.has(message.nodeId)),
        suggestions: state.suggestions.filter((suggestion) => !affected.has(suggestion.nodeId)),
        codexThreads: state.codexThreads.filter((mapping) => !affected.has(mapping.nodeId)),
        selectedNodeId:
          state.selectedNodeId && affected.has(state.selectedNodeId)
            ? replacement
            : state.selectedNodeId,
      };
    }

    case "add-message":
      return {
        ...state,
        messages: [...state.messages, action.message],
      };

    case "update-message":
      return {
        ...state,
        messages: state.messages.map((message) =>
          message.id === action.messageId ? { ...message, ...action.patch } : message,
        ),
      };

    case "set-streaming": {
      const streaming = new Set(state.streamingNodeIds);
      if (action.streaming) {
        streaming.add(action.nodeId);
      } else {
        streaming.delete(action.nodeId);
      }
      return { ...state, streamingNodeIds: Array.from(streaming) };
    }

    case "update-node": {
      const now = nowIso();
      return {
        ...state,
        nodes: state.nodes.map((node) =>
          node.id === action.nodeId ? { ...node, ...action.patch, updatedAt: now } : node,
        ),
      };
    }

    case "replace-suggestions": {
      const now = nowIso();
      const existing = state.suggestions.filter(
        (suggestion) => !(suggestion.nodeId === action.nodeId && suggestion.status === "suggested"),
      );
      const next: ConceptSuggestion[] = action.suggestions.slice(0, 7).map((suggestion, index) => ({
        id: createId("sug"),
        nodeId: action.nodeId,
        label: suggestion.label,
        reason: suggestion.reason,
        priority: suggestion.priority || index + 1,
        difficulty: suggestion.difficulty,
        relation: suggestion.relation,
        status: "suggested",
        createdAt: now,
      }));
      return { ...state, suggestions: [...existing, ...next] };
    }

    case "mark-suggestion-expanded":
      return {
        ...state,
        suggestions: state.suggestions.map((suggestion) =>
          suggestion.id === action.suggestionId
            ? { ...suggestion, status: "expanded" }
            : suggestion,
        ),
      };

    case "set-codex-thread": {
      const now = nowIso();
      const existing = state.codexThreads.find((mapping) => mapping.nodeId === action.nodeId);
      return {
        ...state,
        codexThreads: existing
          ? state.codexThreads.map((mapping) =>
              mapping.nodeId === action.nodeId
                ? { ...mapping, threadId: action.threadId, lastUsedAt: now }
                : mapping,
            )
          : [
              ...state.codexThreads,
              {
                nodeId: action.nodeId,
                threadId: action.threadId,
                createdAt: now,
                lastUsedAt: now,
              },
            ],
      };
    }

    case "update-settings":
      return {
        ...state,
        settings: {
          ...state.settings,
          ...action.patch,
          provider: {
            ...state.settings.provider,
            ...action.patch.provider,
          },
          obsidian: {
            ...state.settings.obsidian,
            ...action.patch.obsidian,
          },
        },
      };

    case "record-sync-status":
      return {
        ...state,
        settings: {
          ...state.settings,
          obsidian: {
            ...state.settings.obsidian,
            lastSyncAt: nowIso(),
            lastSyncStatus: action.status,
          },
        },
      };

    case "reset-demo":
      return createInitialState();

    default:
      return state;
  }
}

export function MindSteedProvider({ children }: { children: ReactNode }) {
  const [state, dispatch] = useReducer(reducer, undefined, loadStateFromBrowser);
  const persistenceReady = useRef(false);

  useEffect(() => {
    let cancelled = false;
    void loadPersistedState()
      .then((persisted) => {
        if (!cancelled && persisted) {
          dispatch({ type: "hydrate", state: persisted });
        }
      })
      .finally(() => {
        if (!cancelled) persistenceReady.current = true;
      });
    return () => {
      cancelled = true;
    };
  }, []);

  useEffect(() => {
    if (!persistenceReady.current) return;
    void savePersistedState(state);
  }, [state]);

  useEffect(() => {
    document.documentElement.dataset.theme = state.settings.theme;
  }, [state.settings.theme]);

  const value = useMemo<MindSteedContextValue>(
    () => ({
      state,
      dispatch,
      actions: {
        createRoot(seedText) {
          dispatch({ type: "create-root", seedText });
        },
        createChild(parentId, title, method, sourceText, sourceMessageId) {
          dispatch({
            type: "create-child",
            parentId,
            title,
            method,
            sourceText,
            sourceMessageId,
          });
        },
        renameNode(nodeId, title) {
          dispatch({ type: "rename-node", nodeId, title });
        },
        deleteNode(nodeId, cascade) {
          dispatch({ type: "delete-node", nodeId, cascade });
        },
      },
    }),
    [state],
  );

  return <MindSteedContext.Provider value={value}>{children}</MindSteedContext.Provider>;
}

export function useMindSteed() {
  const value = useContext(MindSteedContext);
  if (!value) {
    throw new Error("useMindSteed must be used inside MindSteedProvider");
  }
  return value;
}
