import { describe, expect, it } from "vitest";
import type { KnowledgeNode } from "./domain/types";
import {
  autoPromptForNode,
  chatIntentForNodeTurn,
  codexStatusNoticeFromMetadata,
  codexThreadNoticeFromMetadata,
  deleteNodeConfirmationMessage,
  formatCodexStatusDisplay,
  parseGeneratedImageMessage,
  searchKnowledgeNodes,
  serializeGeneratedImageMessage,
  visibleGraphNodes,
} from "./App";

const baseTime = "2026-06-23T18:00:00.000Z";

function node(
  input: Partial<KnowledgeNode> & Pick<KnowledgeNode, "id" | "rootId" | "title">,
): KnowledgeNode {
  return {
    id: input.id,
    parentId: input.parentId ?? null,
    rootId: input.rootId,
    title: input.title,
    summary: input.summary ?? "",
    sourceText: input.sourceText ?? null,
    sourceMessageId: null,
    creationMethod: input.creationMethod ?? "manual",
    nodeType: input.nodeType ?? (input.parentId ? "concept" : "root"),
    childOrder: input.childOrder ?? 0,
    pendingAutoPrompt: input.pendingAutoPrompt ?? false,
    titleAutoGenerated: false,
    titleManuallyEdited: false,
    createdAt: baseTime,
    updatedAt: input.updatedAt ?? baseTime,
  };
}

describe("visibleGraphNodes", () => {
  const nodes = [
    node({ id: "root-a", rootId: "root-a", title: "Root A", creationMethod: "root" }),
    node({ id: "a-child-1", parentId: "root-a", rootId: "root-a", title: "A Child 1" }),
    node({ id: "a-child-2", parentId: "root-a", rootId: "root-a", title: "A Child 2" }),
    node({ id: "a-grandchild", parentId: "a-child-1", rootId: "root-a", title: "A Grandchild" }),
    node({ id: "root-b", rootId: "root-b", title: "Root B", creationMethod: "root" }),
  ];

  it("shows all nodes in global scope", () => {
    expect(visibleGraphNodes(nodes, nodes[3], "global").map((item) => item.id)).toEqual([
      "root-a",
      "a-child-1",
      "a-child-2",
      "a-grandchild",
      "root-b",
    ]);
  });

  it("shows only the current root tree in root scope", () => {
    expect(visibleGraphNodes(nodes, nodes[3], "root").map((item) => item.id)).toEqual([
      "root-a",
      "a-child-1",
      "a-child-2",
      "a-grandchild",
    ]);
  });

  it("shows ancestors, children, and siblings in focus scope", () => {
    expect(visibleGraphNodes(nodes, nodes[1], "focus").map((item) => item.id)).toEqual([
      "root-a",
      "a-child-1",
      "a-child-2",
      "a-grandchild",
    ]);
  });
});

describe("deleteNodeConfirmationMessage", () => {
  const nodes = [
    node({ id: "root-a", rootId: "root-a", title: "Root A", creationMethod: "root" }),
    node({ id: "a-child-1", parentId: "root-a", rootId: "root-a", title: "A Child 1" }),
    node({ id: "a-grandchild", parentId: "a-child-1", rootId: "root-a", title: "A Grandchild" }),
  ];

  it("mentions the descendant count for subtree deletion", () => {
    const message = deleteNodeConfirmationMessage(nodes, "root-a");

    expect(message).toContain("Root A");
    expect(message).toContain("2 个子节点");
    expect(message).toContain("_Deleted");
  });

  it("uses a leaf-node confirmation without descendant text", () => {
    const message = deleteNodeConfirmationMessage(nodes, "a-grandchild");

    expect(message).toContain("A Grandchild");
    expect(message).not.toContain("个子节点");
  });

  it("returns null for an unknown node", () => {
    expect(deleteNodeConfirmationMessage(nodes, "missing")).toBeNull();
  });
});

describe("searchKnowledgeNodes", () => {
  it("returns recently updated nodes for an empty query", () => {
    const nodes = [
      node({ id: "older", rootId: "older", title: "Older", updatedAt: "2026-06-20T18:00:00.000Z" }),
      node({ id: "newer", rootId: "newer", title: "Newer", updatedAt: "2026-06-23T18:00:00.000Z" }),
    ];

    expect(searchKnowledgeNodes(nodes, "").map((item) => item.id)).toEqual(["newer", "older"]);
  });

  it("prioritizes title matches over summary and source text matches", () => {
    const nodes = [
      node({
        id: "summary-hit",
        rootId: "summary-hit",
        title: "Background",
        summary: "Contains GraphQL notes",
      }),
      node({
        id: "title-hit",
        rootId: "title-hit",
        title: "GraphQL",
      }),
      node({
        id: "source-hit",
        rootId: "source-hit",
        title: "Source",
        sourceText: "GraphQL source material",
      }),
    ];

    expect(searchKnowledgeNodes(nodes, "graphql").map((item) => item.id)).toEqual([
      "title-hit",
      "summary-hit",
      "source-hit",
    ]);
  });
});

describe("autoPromptForNode", () => {
  it("uses root source text as the first learning prompt", () => {
    const prompt = autoPromptForNode(
      node({
        id: "root-source",
        rootId: "root-source",
        title: "GraphQL",
        sourceText: "如何系统学习 GraphQL？",
        creationMethod: "root",
      }),
    );

    expect(prompt).toContain("第一轮学习讲解");
    expect(prompt).toContain("如何系统学习 GraphQL？");
  });

  it("falls back to the node title for a manual branch without source text", () => {
    const prompt = autoPromptForNode(
      node({
        id: "manual-branch",
        parentId: "root-source",
        rootId: "root-source",
        title: "Schema 设计",
      }),
    );

    expect(prompt).toBe("请围绕“Schema 设计”开始讲解，给出核心定义、学习路径和可继续展开的分支。");
  });
});

describe("chatIntentForNodeTurn", () => {
  it("uses root_start for the first root turn", () => {
    expect(
      chatIntentForNodeTurn(
        node({
          id: "root-start",
          rootId: "root-start",
          title: "Root",
          nodeType: "root",
          pendingAutoPrompt: true,
        }),
        0,
      ),
    ).toBe("root_start");
  });

  it("uses branch_start for pending concept nodes", () => {
    expect(
      chatIntentForNodeTurn(
        node({
          id: "branch-start",
          parentId: "root-start",
          rootId: "root-start",
          title: "Branch",
          pendingAutoPrompt: true,
        }),
        0,
      ),
    ).toBe("branch_start");
  });

  it("uses follow_up_as_branch for branches created from selected answer text", () => {
    expect(
      chatIntentForNodeTurn(
        node({
          id: "selection-branch",
          parentId: "root-start",
          rootId: "root-start",
          title: "Selected idea",
          creationMethod: "selection",
          pendingAutoPrompt: true,
        }),
        0,
      ),
    ).toBe("follow_up_as_branch");
  });

  it("uses follow_up after a conversation has started", () => {
    expect(
      chatIntentForNodeTurn(
        node({
          id: "follow-up",
          rootId: "follow-up",
          title: "Root",
          nodeType: "root",
        }),
        2,
      ),
    ).toBe("follow_up");
  });
});

describe("codexThreadNoticeFromMetadata", () => {
  it("only shows a Codex diagnostic when resume falls back to a new thread", () => {
    expect(codexThreadNoticeFromMetadata({ codexThreadStatus: "resumed" })).toBeNull();
    expect(codexThreadNoticeFromMetadata({ codexThreadStatus: "started" })).toBeNull();

    expect(
      codexThreadNoticeFromMetadata({
        codexThreadStatus: "resume-fallback",
        codexThreadResumeError: "Codex app-server error",
      }),
    ).toContain("Codex app-server error");
  });
});

describe("codexStatusNoticeFromMetadata", () => {
  it("formats reportable Codex non-message item status metadata", () => {
    expect(codexStatusNoticeFromMetadata({})).toBeNull();
    expect(
      codexStatusNoticeFromMetadata({
        codexStatus: "started",
        codexStatusKind: "command_execution",
        codexStatusLabel: "ls -la",
      }),
    ).toBe("Codex Local reported command execution started: ls -la");
  });

  it("formats blocked Codex tool-work metadata as a stop notice", () => {
    expect(
      codexStatusNoticeFromMetadata({
        codexStatus: "blocked",
        codexStatusKind: "command_execution",
        codexStatusLabel: "ls -la",
        codexStatusSeverity: "warning",
      }),
    ).toBe(
      "Codex Local tried to perform command execution: ls -la. OpenMindSteed stopped this learning turn to avoid local tool or command work.",
    );
  });
});

describe("formatCodexStatusDisplay", () => {
  it("includes setup action when Codex is not signed in", () => {
    const display = formatCodexStatusDisplay({
      binary: "/Applications/Codex.app/Contents/Resources/codex",
      version: "codex-cli 0.142.0",
      loginStatus: "No active session",
      loggedIn: false,
      appServerCompatible: true,
      compatibilityNote: "Within tested Codex CLI range >=0.142.0 <0.143.0.",
    });

    expect(display).toContain("Run `codex login`");
    expect(display).toContain("sign in with ChatGPT");
    expect(display).toContain("/Applications/Codex.app/Contents/Resources/codex");
  });

  it("surfaces compatibility warnings for untested Codex versions", () => {
    const display = formatCodexStatusDisplay({
      binary: "codex",
      version: "codex-cli 0.143.0",
      loginStatus: "Logged in",
      loggedIn: true,
      appServerCompatible: false,
      compatibilityNote: "Outside tested Codex CLI range >=0.142.0 <0.143.0.",
    });

    expect(display).toContain("Compatibility warning");
    expect(display).toContain("Outside tested Codex CLI range");
  });
});

describe("generated image messages", () => {
  it("round-trips generated image payloads through the legacy message prefix", () => {
    const message = serializeGeneratedImageMessage({
      id: "img-a",
      url: "https://example.com/image.png",
      mimeType: "image/png",
      sourceUrl: "https://provider.example.com/image.png",
      localPath: "/Users/me/Library/Application Support/OpenMindSteed/generated-images/img-a.png",
      byteLength: 1024,
      storedAt: "2026-06-23T18:00:00.000Z",
      prompt: "diagram",
      size: "1280x1280",
      quality: "standard",
    });

    expect(parseGeneratedImageMessage(message)).toMatchObject({
      id: "img-a",
      url: "https://example.com/image.png",
      localPath: "/Users/me/Library/Application Support/OpenMindSteed/generated-images/img-a.png",
      prompt: "diagram",
    });
    expect(
      parseGeneratedImageMessage("__mindsteed_generated_image__:https://example.com/old.png"),
    ).toMatchObject({
      url: "https://example.com/old.png",
      sourceUrl: "https://example.com/old.png",
    });
    expect(parseGeneratedImageMessage("plain text")).toBeNull();
  });
});
